window:
  dimensions:
    columns: 0
    lines: 0
  padding:
    x: 2
    y: 2
  dynamic_padding: false
  decorations: none
  start_maximized: true

scrolling:
  history: 10000
  multiplier: 3
  faux_multiplier: 3
  auto_scroll: false

tabspaces: 8

font:
  size: 13.0
  normal:
    family: Hasklig
    style: Regular

  bold:
    family: Hasklig
    style: Bold

  italic:
    family: Hasklig
    style: Italic

  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  use_thin_strokes: true

render_timer: false

persistent_logging: false

draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: '0x1c1f20'
    foreground: '0xc4c8c6'
  cursor:
    cursor: '0xcccccc'
  normal:
    black:   '0x27292d'
    red:     '0xdc595d'
    green:   '0xa9b75d'
    yellow:  '0xf6c76b'
    blue:    '0x7aa1c0'
    magenta: '0xba8dba'
    cyan:    '0x79c1b8'
    white:   '0x6f7780'
  bright:
    black:   '0x1c1f20'
    red:     '0xea9054'
    green:   '0x4d8c5f'
    yellow:  '0xa5812d'
    blue:    '0x625a88'
    magenta: '0x5e415a'
    cyan:    '0x79c1b8'
    white:   '0xc4c8c6'
  indexed_colors: []

visual_bell:
  animation: EaseOutExpo
  duration: 0
  color: '0xffffff'

background_opacity: 1.0

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: false

  url:
    modifiers: Command

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: false

dynamic_title: true

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: true

shell:
  program: /usr/local/bin/zsh

# Windows 10 ConPTY backend (Windows only)
#
# This will enable better color support and may resolve other issues,
# however this API and its implementation is still young and so is
# disabled by default, as stability may not be as good as the winpty
# backend.
#
# Alacritty will fall back to the WinPTY automatically if the ConPTY
# backend cannot be initialized.
enable_experimental_conpty_backend: false
alt_send_esc: true


key_bindings:
  - { key: Key0,     mods: Command, action: ResetFontSize    }
  - { key: Equals,   mods: Command, action: IncreaseFontSize }
  - { key: Add,      mods: Command, action: IncreaseFontSize }
  - { key: Minus,    mods: Command, action: DecreaseFontSize }
  - { key: Q,        mods: Command, action: Quit             }
  - { key: W,        mods: Command, action: Quit             }

  - { key: PageUp,                  chars: "\x1b[5~"         }
  - { key: PageDown,                chars: "\x1b[6~"         }
  - { key: Back,                    chars: "\x7f"            }
  - { key: Back,     mods: Alt,     chars: "\x1b\x7f"        }
  - { key: Back,     mods: Command, chars: "\x15"            }
  - { key: Left,     mods: Control, chars: "\x1b[1;5D"       }
  - { key: Left,     mods: Alt,     chars: "\x1bb"           }
  - { key: Left,     mods: Command, chars: "\x01"            }
  - { key: Right,    mods: Control, chars: "\x1b[1;5C"       }
  - { key: Right,    mods: Alt,     chars: "\x1bf"           }
  - { key: Right,    mods: Command, chars: "\x05"            }

  - { key: Key0,        mods: Control, chars: "\x1b[27;5;48~"   }
  - { key: Key1,        mods: Control, chars: "\x1b[27;5;49~"   }
  - { key: Key2,        mods: Control, chars: "\x1b[27;5;50~"   }
  - { key: Key3,        mods: Control, chars: "\x1b[27;5;51~"   }
  - { key: Key4,        mods: Control, chars: "\x1b[27;5;52~"   }
  - { key: Key5,        mods: Control, chars: "\x1b[27;5;53~"   }
  - { key: Key6,        mods: Control, chars: "\x1b[27;5;54~"   }
  - { key: Key7,        mods: Control, chars: "\x1b[27;5;55~"   }
  - { key: Key8,        mods: Control, chars: "\x1b[27;5;56~"   }
  - { key: Key9,        mods: Control, chars: "\x1b[27;5;57~"   }
